from . import ir_actions
from . import res_partner
from . import project
from . import pull_requests
from . import batch
from . import project_freeze
from . import stagings_create
from . import staging_cancel
from . import events_sources
from . import crons
